version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'

      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /home/hasibur/db-data/mysql_with_php:/var/lib/mysql
  phpmyadmin:
    container_name: "admin-tool"
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8081:80
    environment:
      MYSQL_ROOT_PASSWORD: password
volumes:
  my-db:
